"""superbrain — the command line over the Enterprise AI Engineer Pack.

    sb stats                     what is in the pack
    sb search "kafka cdc"        rank catalogued repos against a query
    sb route "harden our API"    specialists + skills + repos + pipeline
    sb brief "harden our API"    the same, as a paste-ready agent brief
    sb verify                    resolve every repo with git ls-remote
    sb prune --apply             delete entries that did not resolve
    sb doctor                    integrity check over the pack itself
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from collections import Counter

from . import catalog as cat
from . import router as rt
from . import validate as val


def _load():
    return cat.load_catalog(), cat.load_agents(), cat.load_skills()


# ---------------------------------------------------------------- stats ----

def cmd_stats(args) -> int:
    repos, agents, skills = _load()
    uniq = cat.unique_slugs(repos)
    record = cat.load_verification()
    results = record.get("results", {})
    verified_ok = sum(1 for s in uniq if results.get(s, {}).get("ok"))
    verified_bad = sum(1 for s in uniq if s in results and not results[s].get("ok"))

    if args.json:
        print(json.dumps({
            "entries": len(repos), "unique_repos": len(uniq),
            "domains": len({r.domain for r in repos}),
            "agents": len(agents), "skills": len(skills),
            "verified_ok": verified_ok, "verified_failed": verified_bad,
            "unchecked": len(uniq) - verified_ok - verified_bad,
            "checked_at": record.get("checked_at"),
        }, indent=2))
        return 0

    by_domain = Counter(r.domain for r in repos)
    print(f"catalog entries : {len(repos)}")
    print(f"unique repos    : {len(uniq)}")
    print(f"domains         : {len(by_domain)}")
    print(f"agents          : {len(agents)}")
    print(f"skills          : {len(skills)}")
    print()
    for domain, n in sorted(by_domain.items(), key=lambda kv: -kv[1]):
        print(f"  {n:>4}  {domain}")
    print()
    if record.get("checked_at"):
        print(f"verified        : {verified_ok} ok, {verified_bad} failed, "
              f"{len(uniq) - verified_ok - verified_bad} unchecked "
              f"(last run {record['checked_at']})")
    else:
        print("verified        : never run — `sb verify` before quoting this catalog")
    return 0


# --------------------------------------------------------------- search ----

def cmd_search(args) -> int:
    repos, _, _ = _load()
    hits = rt.search_repos(repos, " ".join(args.query), limit=args.limit, domain=args.domain)
    if args.json:
        print(json.dumps([h.to_dict() for h in hits], indent=2))
        return 0
    if not hits:
        print("no matches")
        return 1
    for h in hits:
        r = h.item
        print(f"{h.score:>6.1f}  {r.slug}")
        print(f"        {r.note}")
        print(f"        {r.domain} · {', '.join(r.tags)} · {r.url}")
    return 0


# ---------------------------------------------------------------- route ----

def cmd_route(args) -> int:
    repos, agents, skills = _load()
    result = rt.route(" ".join(args.task), repos, agents, skills,
                      repo_limit=args.limit, agent_limit=args.agents)
    if args.json:
        print(json.dumps(result, indent=2))
        return 0
    print(f"task     : {result['task']}")
    print(f"shape    : {result['shape']}")
    print(f"pipeline : {' -> '.join(result['pipeline'])}")
    print(f"tokens   : {', '.join(result['tokens']) or '(none matched)'}")
    print()
    print("specialists")
    for a in result["agents"] or []:
        print(f"  {a['score']:>6.1f}  {a['name']}")
    if not result["agents"]:
        print("  (none matched — falling back to the pipeline roles above)")
    print()
    if result["skills"]:
        print("skills")
        for s in result["skills"]:
            print(f"  {s['score']:>6.1f}  {s['name']}")
        print()
    print("reference repositories")
    for r in result["repos"]:
        print(f"  {r['score']:>6.1f}  {r['slug']:<48} {r['note'][:60]}")
    return 0


# ---------------------------------------------------------------- brief ----

BRIEF = """\
# Task brief — generated by superbrain

**Task:** {task}
**Shape:** {shape}
**Proposed pipeline:** {pipeline}

## Specialists to spawn
{agents}

## Skills that apply
{skills}

## Reference implementations to consult before writing code
{repos}

## Standing rules for this task
- Read the referenced code before copying its shape. A repo in this list is
  evidence of a working pattern, not a licence to vendor it.
- Verify by running. Exit code 0 is not proof the behaviour is correct.
- State what you did not do. Partial work reported as complete is the failure
  mode this pack exists to prevent.
- Check licence and provenance before any code is reused in a deliverable.
"""


def cmd_brief(args) -> int:
    repos, agents, skills = _load()
    result = rt.route(" ".join(args.task), repos, agents, skills,
                      repo_limit=args.limit, agent_limit=args.agents)
    fmt_agents = "\n".join(
        f"- **{a['name']}** — {a.get('description', '')[:150]}" for a in result["agents"]
    ) or "- (no specialist matched; use the pipeline roles: " + ", ".join(result["pipeline"]) + ")"
    fmt_skills = "\n".join(f"- {s['name']}" for s in result["skills"]) or "- (none matched)"
    fmt_repos = "\n".join(
        f"- [{r['slug']}]({r['url']}) — {r['note']}" for r in result["repos"]
    ) or "- (no catalogued repo matched; widen the query)"
    print(BRIEF.format(
        task=result["task"], shape=result["shape"],
        pipeline=" → ".join(result["pipeline"]),
        agents=fmt_agents, skills=fmt_skills, repos=fmt_repos,
    ))
    return 0


# --------------------------------------------------------------- verify ----

def cmd_verify(args) -> int:
    repos, _, _ = _load()
    slugs = cat.unique_slugs(repos)
    record = cat.load_verification()
    results = record.get("results", {})

    if args.only_new:
        slugs = [s for s in slugs if s not in results]
    if args.only_failed:
        slugs = [s for s in slugs if s in results and not results[s].get("ok")]
    if args.limit:
        slugs = slugs[: args.limit]

    if not slugs:
        print("nothing to check")
        return 0

    started = time.time()
    failures: list[val.CheckResult] = []

    def progress(done: int, total: int, res: val.CheckResult) -> None:
        if not res.ok:
            failures.append(res)
        if args.quiet:
            return
        bad = len(failures)
        sys.stderr.write(f"\r  checked {done}/{total}  failed {bad}   ")
        sys.stderr.flush()

    checked = val.check_all(slugs, workers=args.workers, timeout=args.timeout,
                            progress=progress)
    if not args.quiet:
        sys.stderr.write("\n")

    for slug, res in checked.items():
        results[slug] = res.to_dict()
    record["results"] = results
    record["checked_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    cat.save_verification(record)

    ok = sum(1 for s in slugs if results[s]["ok"])
    print(f"checked {len(slugs)} repos in {time.time() - started:.1f}s: "
          f"{ok} resolved, {len(slugs) - ok} failed")
    for res in sorted(failures, key=lambda r: r.slug):
        print(f"  FAIL  {res.slug:<50} {res.detail}")
    return 0 if not failures else 2


# ---------------------------------------------------------------- prune ----

def cmd_prune(args) -> int:
    repos, _, _ = _load()
    record = cat.load_verification()
    results = record.get("results", {})
    if not results:
        print("no verification record — run `sb verify` first")
        return 1
    dead = {s for s in cat.unique_slugs(repos)
            if s in results and not results[s].get("ok")}
    if not dead:
        print("nothing to prune")
        return 0
    removed = val.prune_catalog(cat.CATALOG_DIR, dead, dry_run=not args.apply)
    total = sum(removed.values())
    verb = "removed" if args.apply else "would remove"
    for name, n in sorted(removed.items()):
        print(f"  {verb} {n:>3} from {name}")
    print(f"{verb} {total} entries ({len(dead)} distinct repos)")
    if not args.apply:
        print("re-run with --apply to write the changes")
    return 0


# --------------------------------------------------------------- doctor ----

def cmd_doctor(args) -> int:
    problems: list[str] = []
    try:
        repos, agents, skills = _load()
    except cat.CatalogError as exc:
        print(f"FAIL  catalog does not parse: {exc}")
        return 1

    counts = Counter(r.slug for r in repos)
    dupes_in_domain = Counter((r.slug, r.domain) for r in repos)
    for (slug, domain), n in dupes_in_domain.items():
        if n > 1:
            problems.append(f"duplicate entry {slug} appears {n}x in {domain}")

    for r in repos:
        if not r.tags:
            problems.append(f"{r.slug} ({r.domain}) has no tags")
        if not r.note:
            problems.append(f"{r.slug} ({r.domain}) has no note")

    names = Counter(a.name for a in agents)
    for name, n in names.items():
        if n > 1:
            problems.append(f"duplicate agent name {name} ({n}x)")
    for a in agents:
        if not a.description:
            problems.append(f"agent {a.name} has no description")
        if not a.triggers:
            problems.append(f"agent {a.name} has no triggers — it can never be routed to")
    for s in skills:
        if not s.description:
            problems.append(f"skill {s.name} has no description")

    record = cat.load_verification()
    unchecked = [s for s in cat.unique_slugs(repos) if s not in record.get("results", {})]

    print(f"catalog  : {len(repos)} entries, {len(counts)} unique repos")
    print(f"agents   : {len(agents)}")
    print(f"skills   : {len(skills)}")
    print(f"unchecked: {len(unchecked)} repos have never been resolved")
    if problems:
        print(f"\n{len(problems)} problem(s):")
        for p in problems[: args.limit]:
            print(f"  - {p}")
        if len(problems) > args.limit:
            print(f"  ... and {len(problems) - args.limit} more")
        return 1
    print("\nno structural problems found")
    return 0


# --------------------------------------------------------------- agents ----

def cmd_agents(args) -> int:
    _, agents, _ = _load()
    if args.json:
        print(json.dumps([{"name": a.name, "description": a.description,
                           "domains": list(a.domains), "triggers": list(a.triggers)}
                          for a in agents], indent=2))
        return 0
    for a in agents:
        print(f"{a.name}")
        print(f"  {a.description[:150]}")
        print(f"  domains: {', '.join(a.domains) or '-'}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="sb", description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="command", required=True)

    s = sub.add_parser("stats", help="what is in the pack")
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_stats)

    s = sub.add_parser("search", help="rank catalogued repos against a query")
    s.add_argument("query", nargs="+")
    s.add_argument("--domain")
    s.add_argument("--limit", type=int, default=15)
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_search)

    s = sub.add_parser("route", help="task -> specialists, skills, repos, pipeline")
    s.add_argument("task", nargs="+")
    s.add_argument("--limit", type=int, default=12)
    s.add_argument("--agents", type=int, default=4)
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_route)

    s = sub.add_parser("brief", help="route, formatted as a paste-ready agent brief")
    s.add_argument("task", nargs="+")
    s.add_argument("--limit", type=int, default=10)
    s.add_argument("--agents", type=int, default=4)
    s.set_defaults(func=cmd_brief)

    s = sub.add_parser("verify", help="resolve every repo with git ls-remote")
    s.add_argument("--workers", type=int, default=12)
    s.add_argument("--timeout", type=int, default=25)
    s.add_argument("--limit", type=int, default=0)
    s.add_argument("--only-new", action="store_true", help="skip repos already recorded")
    s.add_argument("--only-failed", action="store_true", help="recheck previous failures")
    s.add_argument("--quiet", action="store_true")
    s.set_defaults(func=cmd_verify)

    s = sub.add_parser("prune", help="drop entries that failed verification")
    s.add_argument("--apply", action="store_true")
    s.set_defaults(func=cmd_prune)

    s = sub.add_parser("doctor", help="integrity check over the pack")
    s.add_argument("--limit", type=int, default=25)
    s.set_defaults(func=cmd_doctor)

    s = sub.add_parser("agents", help="list specialist agents")
    s.add_argument("--json", action="store_true")
    s.set_defaults(func=cmd_agents)
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
